### ISSUE TITLE
Issue after Login

### ISSUE THREAD

**Issue by germanbeast** [developeregrem/pve#67]
Hello together,

i became a Oops! An Error Occurred
The server returned a "500 Internal Server Error" after Login in fewohbee

PHP Error Code below

`fewohbee-dockerized-php-1    | {"message":"Uncaught PHP Exception Error: \"Call                                                                                                                       to a member function getId() on null\" at /var/www/html/fewohbee/src/Controller/                                                                                                                      ReservationServiceController.php line 71","context":{"exception":{"class":"Error                                                                                                                      ","message":"Call to a member function getId() on null","code":0,"file":"/var/ww                                                                                                                      w/html/fewohbee/src/Controller/ReservationServiceController.php:71"}},"level":50                                                                                                                      0,"level_name":"CRITICAL","channel":"request","datetime":"2022-11-09T17:30:21.13                                                                                                                      7984+01:00","extra":{}}
fewohbee-dockerized-php-1    | {"message":"Stored the security token in the sess                                                                                                                      ion.","context":{"key":"_security_main"},"level":100,"level_name":"DEBUG","chann                                                                                                                      el":"security","datetime":"2022-11-09T17:30:21.174193+01:00","extra":{}}
fewohbee-dockerized-php-1    | 172.18.0.3 -  09/Nov/2022:17:30:21 +0100 "GET /in                                                                                                                      dex.php" 500
`

**Comment by developeregrem** [comment]
Hi @germanbeast 
is this a fresh install without loading some initial test data?
If yes I recommend to load test data:
```
docker-compose exec --user www-data php /bin/sh -c "php fewohbee/bin/console doctrine:fixtures:load --append"
```
Alex
